#!/bin/zsh

d=${0:a:h}
s=$d/scpt
j=$d/json
mkdir -p $j
f=$j/blogger_body.json

cd $d
mkdir -p {md,html,json}
git pull

$s/blogger_help.sh
$s/blogger_access.sh
#$s/token_refresh.sh

case $1 in
	-u)
		$s/blogger_update.sh
	;;
	"")
		$s/blogger_post.sh
	;;
	-a)
		$s/blogger_auto.sh
	;;
esac

cd $d
git add .
git commit -m "update:auto"
git push -f
